### ISSUE TITLE
Test no eviction annotation for executor pod

### ISSUE THREAD

**Issue by efi-rfauzan** [efi-rfauzan/task-management#37]
### Staging

Add annotation shown on the snippet below onto the config.toml of gitlab runner on the executor section.
```
spec:
  template:
    metadata:
      annotations:
        karpenter.sh/do-not-evict: "true"
```

But, since we are using kubernetes, we cannot directly modify the config.toml. The modification happens on values.yaml helm chart. The config should look like:
```
runners:
  config: |
      [[runners]]
          [runners.kubernetes]
              [runners.kubernetes.pod_annotations]
                  karpenter.sh/do-not-evict = "true"
```

References:
- https://karpenter.sh/preview/concepts/deprovisioning/#pod-level-controls
- https://docs.gitlab.com/runner/executors/kubernetes.html#other-configtoml-settings
- https://docs.gitlab.com/runner/configuration/advanced-configuration.html#the-runnerskubernetes-section
