### ISSUE TITLE
Schedule runner pods to EKS managed node first

### ISSUE THREAD

**Issue by efi-rfauzan** [efi-rfauzan/task-management#40]
Eks managed nodes seems to be underutilized while karpenter nodes are over utilized. It is not cost effective, because it prevents the karpenter nodes from scaling down.

To address this issue, we can prioritize the EKS nodes over the Karpenter nodes for scheduling runner pods. That can be done with nodeAffinity, preferredDuringSchedulingIgnoredDuringExecution.

For example
```
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1
        preference:
          matchExpressions:
          - key: another-node-label-key
            operator: In
            values:
            - another-node-label-value
```

References:
- https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
